# Generated by Django 4.1.3 on 2022-11-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee',
            new_name='employer',
        ),
    ]
