# Generated by Django 4.1.3 on 2022-11-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0002_rename_employee_employee_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_user',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2)], default=0, max_length=1),
        ),
    ]
