# Generated by Django 4.1.3 on 2022-11-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0003_employee_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='nihal chutiya hai'),
        ),
    ]
