# Generated by Django 4.1.3 on 2022-11-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empDetail', '0004_alter_employee_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_user',
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
